name: test

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Setup repo
        uses: actions/checkout@v2

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      - name: Run linter
        run: deno task lint

      - name: Run tests
        run: deno task test

      - name: Create coverage report
        run: deno coverage --lcov cov_profile/ > cov.lcov

      - name: Upload coverage report
        uses: codecov/codecov-action@v2
        with:
          files: cov.lcov
          fail_ci_if_error: true
